export const ModelEventNames = {
    ASSETS_LOADED: "ASSETS_LOADED",
    ON_UPDATE_FPS: "ON_UPDATE_FPS",
    SPIN_REEL: "SPIN_REEL",
    STOP_REEL: "STOP_REEL",
    WINNING_ANIMATION_END: "WINNING_ANIMATION_END"
};