export const COMMANDS_NAMES = {
    LOAD_ASSETS: "LOAD_ASSETS",
    DRAW_UI: "DRAW_UI",
    DRAW_GAME_SCENE: "DRAW_GAME_SCENE",
    DRAW_WINNING: "DRAW_WINNING",
    DRAW_FPS: "DRAW_FPS",
    START_UPDATE_FPS: "START_UPDATE_FPS",
    START_WINNING_ANIMATION: "START_WINNING_ANIMATION",
    STOP_WINNING_ANIMATION: "STOP_WINNING_ANIMATION",
    UPDATE_FPS: "UPDATE_FPS",
    START_SPIN: "START_SPIN",
    SPIN: "SPIN",
    STOP_SPIN: "STOP_SPIN",
    STOP_SPIN_TICKER: "STOP_SPIN_TICKER",
    DISABLE_UI: "DISABLE_UI",
    PLAY_WINNINGS: "PLAY_WINNINGS",
    RESIZE: "RESIZE"
};
