export const COMMANDS_NAMES = {
    LOAD_ASSETS: "LOAD_ASSETS",
    DRAW_UI: "DRAW_UI",
    DRAW_FPS: "DRAW_FPS",
    START_UPDATE_FPS: "START_UPDATE_FPS",
    UPDATE_FPS: "UPDATE_FPS",
    START_SPIN: "START_SPIN"
};
